### PR TITLE
Stop using feof for checking if socket is closed

### PR DESCRIPTION
**Pull request by psafarov**
Solves #58

### CODE REVIEW

**Comment by bwoebi** [comment]
Re-check the issue exposed by #40 before merging this one.

**Comment by psafarov** [comment]
From what I understood, `feof` tells if data was written to buffer, which happens to be an indication of a closed socket on some systems, however not on all of them, like in my case. So if `fwrite` is not a good, then maybe `fflush` is. It flushes data from buffer and returns `false` on failure, which might be an actual indication of a broken connection.

**Comment by trowski** [comment]
I question calling `fflush()` after every write. Seems like it would be terrible for performance.

Based on the tests you changed, it looks like removing the EOF check results in multiple write attempts being made before the stream is detected as closed. Can the EOF check after the write be kept? I would expect this to return false. What about the `is_resource()` call?

**Comment by psafarov** [comment]
It does have to affect performance negatively, but I proposed it anyway because the `feof` already prevented from buffer usage by throwing an exception, thus it is at least a lesser evil.

**Comment by psafarov** [comment]
And keeping EOF check after the write would not fix the problem. I ran a script as a systemd unit and `feof` was always true, either before or after the write.

**Comment by psafarov** [comment]
Resolved by #60

**Pull request closed without merging**
