### PR TITLE
Update ResourceOutputStream.php, bug: #14

### PR DESCRIPTION
**Pull request by umbri**
https://github.com/amphp/byte-stream/issues/14

### CODE REVIEW

**Comment by kelunik** [comment]
Not sure about that. Should we just is `if ($this->chunkSize) { ... } else { ... }`?

**Comment by umbri** [comment]
I am not sure, if PHP is doing it right, I get really strange errors.

**Comment by umbri** [comment]
@kelunik I think is ```if ($this->chunkSize) { ... } else { ... }``` is better

**Comment by trowski** [comment]
@kelunik Yes, I think so if we want to allow setting chunk size. Apparently passing `null` is coerced into 0 and causes weird behavior. I would also make the default size 65536 (needs updating in `ResourceInputStream` as well).

**Comment by umbri** [comment]
Close this ?

**Comment by umbri** [comment]
https://github.com/amphp/byte-stream/commit/ea135f26d04a110f15468a436be96df01f34252d fix this

**Comment by kelunik** [comment]
@trowski Default size can be `null`, no?

**Comment by trowski** [comment]
Yeah, `null` is fine for the default.

**Pull request closed without merging**
