### PR TITLE
Replace Message with explicit readAll function

### PR DESCRIPTION
**Pull request by kelunik**
Currently there's no possibility anymore to directly create a `ReadableStream` from an `Amp\Stream`, see `ReadAllTest`. Dunno whether we need that.

### CODE REVIEW

**Comment by bwoebi** [comment]
Uh, creating a `ReadableStream` from `Amp\Stream` is already about half of the point of `Message`...
Also, I suspect your `readAll()` implementation will be quite a bit slower with many chunks.

**Comment by kelunik** [comment]
> Also, I suspect your readAll() implementation will be quite a bit slower with many chunks.

What's your proposal that works with only coding to an interface?

**Comment by trowski** [comment]
`Message` is useful for creating an instance of `ReadableStream` from an arbitrary source of bytes. Aerys uses it to create bodies for requests and websocket messages, both cases where the data source is a socket, but of course you cannot directly pass that socket to the consumer. A `Stream` instance is just a convenient method of providing that data in a way that can indicate back-pressure and provides a means of buffering unconsumed data.

`Message` implements `Promise` to provide an elegant way to consume the entire contents of a stream in Aerys and anywhere else discrete messages are used. Would we want to force users to call another function for that common use-case? `$data = yield $message` vs. `$data = yield ByteStream\readAll($message)` @bwoebi Implementing `Promise` in `Message` seemed important to you, do you have thoughts here?

**Comment by kelunik** [comment]
@trowski I created this PR, because you wanted a more explicit way than the `Message implements Promise` way.

**Comment by kelunik** [comment]
Closing due to #3.

**Pull request closed without merging**
