### PR TITLE
Add base64 streams and drop PHP 7.0

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by kelunik** [comment]
Seems like I already built something similar before: https://github.com/kelunik/streaming-base64

**Comment by trowski** [comment]
Should we put these in a sub-namespace like `Amp\ByteStream\Base64`?

**Comment by kelunik** [comment]
I don't really care, but sounds like a good idea.

**Comment by kelunik** [comment]
@trowski This should be ready now. I've dropped PHP 7.0 support due to `: void` being required on `setUp` on newer versions, but being unsupported on PHP 7.0. I've tried to use `amphp/phpunit-util@1.4` with `setUpAsync` instead, but that requires PHP 7.1, too.

**Pull request merged**
